### ISSUE TITLE
Add endpoint / field to inform about the locked wallet

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#33]
On startup when auto-unlock is not enabled, the Lightning wallet is locked.

I would like to have an extra endpoint or a field in `ln_info_lite` to see if the wallet is locked.

**Comment by fusion44** [comment]
I don't really want to add a field to `ln_info_lite` because you only can get this info when the wallet is unlocked.

### Proposal: 
All endpoints, while locked, will return http status `409 Conflict`. Additionally, when establishing the SSE connection, clients will receive a new event type called `wallet_status` with one boolean field `locked`. This way there is no additional endpoint needed, just to see whether the wallet is locked or not.

**Comment by cstenglein** [comment]
The SSE event sounds awesome!

I'm not sure if the `409 conflict` though. How about `423 Locked` :)

& a question: What endpoints won't work when the wallet is locked? Am I able to receive on-chain transactions etc.?

**Comment by fusion44** [comment]
See #34 for progress on this.
