### ISSUE TITLE
Add endpoint to unlock wallet

### ISSUE THREAD

**Issue by cstenglein** [fusion44/blitz_api#34]
If the wallet is locked, I would like to be able to unlock it over the webUI.

**Comment by cstenglein** [comment]
@rootzoll important issue

**Comment by fusion44** [comment]
OK, this took longer than expected, but it made the startup sequence more robust. Now the startup sequence now takes into account, when the wallet is locked and defers necessary lightning steps until a successful unlock.

@cstenglein Please test this. Especially the SSE endpoint after an unlock. For me locally, it works well.

**Comment by fusion44** [comment]
One more caveat, currently, you can only connect to the SSE endpoint when the wallet is unlocked! Will take additional effort to make this work later.

**Comment by fusion44** [comment]
OK, I think this issue is pretty much implemented now. When someone connects to the SSE endpoint and the wallet is locked a message with event name `wallet_lock_status` type is sent:
```js
// only sent when a new SSE connection is established and the wallet is locked at the same time
event: wallet_lock_status
data: {"locked": true}
```
When the wallet is unlocked either through SSH or the API, another event is sent:
```js
// sent always when a new connection is established when the wallet is unlocked, or 
// it is sent when the wallet was unlocked after connection was established
event: wallet_lock_status
data: {"locked": false}
```

It is always the first thing the client receives. After the unlock event, the usual warmup data is sent.
